"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ppt = exports.pdf = exports.doc = exports.json = exports.zip = exports.txt = exports.xls = exports.mp3 = exports.jpg = exports.html = exports.file = exports.exe = exports.mp4 = exports.avi = exports.bin = exports.folder = void 0;
var folder_png_1 = require("./folder.png");
exports.folder = folder_png_1.default;
var bin_png_1 = require("./bin.png");
exports.bin = bin_png_1.default;
var avi_png_1 = require(".//avi.png");
exports.avi = avi_png_1.default;
var mp4_png_1 = require("./mp4.png");
exports.mp4 = mp4_png_1.default;
var exe_png_1 = require("./exe.png");
exports.exe = exe_png_1.default;
var file_png_1 = require("./file.png");
exports.file = file_png_1.default;
var html_png_1 = require("./html.png");
exports.html = html_png_1.default;
var jpg_png_1 = require("./jpg.png");
exports.jpg = jpg_png_1.default;
var mp3_png_1 = require("./mp3.png");
exports.mp3 = mp3_png_1.default;
var xls_png_1 = require("./xls.png");
exports.xls = xls_png_1.default;
var txt_png_1 = require("./txt.png");
exports.txt = txt_png_1.default;
var zip_png_1 = require("./zip.png");
exports.zip = zip_png_1.default;
var json_png_1 = require("./json.png");
exports.json = json_png_1.default;
var doc_png_1 = require("./doc.png");
exports.doc = doc_png_1.default;
var pdf_png_1 = require("./pdf.png");
exports.pdf = pdf_png_1.default;
var ppt_png_1 = require("./ppt.png");
exports.ppt = ppt_png_1.default;
//# sourceMappingURL=index.js.map